id: AE4E025F5
title: 'A Drop of Sunshine: A Guru Yoga for Lord Marpa'
type: translation
pechas:
- IF191ED98
- I6B4924E7
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:01:16.489907
  last_modified_at: 2023-01-04 13:01:16.489928
  collections:
  - Marpa Lotsāwa Series
  - Works of Tibetan Masters
alignment_to_base:
  IF191ED98/1353: 4A5C
  I6B4924E7/A367: 4A5C
